{% set name = "brian2genn" %}
{% set version = "1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Brian2GeNN-{{ version }}.tar.gz
  sha256: f0c42e5fe3ecfd6d373353caa5a431e13284288b07340e88f1c2829f4de53965

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - brian2 >=2.4.2
    - python >={{ python_min }}
    - six

test:
  imports:
    - brian2genn
    - brian2genn.sphinxext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/brian-team/brian2genn
  summary: An interface to use the GeNN framework as a device in Brian 2
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
